// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/founder-message/Current.tsx": () => import("../components/mockups/founder-message/Current.tsx"),
  "./components/mockups/founder-message/Reference.tsx": () => import("../components/mockups/founder-message/Reference.tsx"),
  "./components/mockups/b4p-homepage-hero/Current.tsx": () => import("../components/mockups/b4p-homepage-hero/Current.tsx"),
  "./components/mockups/b4p-homepage-hero/Refined.tsx": () => import("../components/mockups/b4p-homepage-hero/Refined.tsx"),
  "./components/mockups/header-redesign/ModernDesktopMenus.tsx": () => import("../components/mockups/header-redesign/ModernDesktopMenus.tsx"),
  "./components/mockups/homepage-sections/CurrentEDFeature.tsx": () => import("../components/mockups/homepage-sections/CurrentEDFeature.tsx"),
  "./components/mockups/homepage-sections/CurrentPartners.tsx": () => import("../components/mockups/homepage-sections/CurrentPartners.tsx"),
  "./components/mockups/homepage-sections/CurrentPillars.tsx": () => import("../components/mockups/homepage-sections/CurrentPillars.tsx"),
  "./components/mockups/homepage-sections/RefinedEDFeature.tsx": () => import("../components/mockups/homepage-sections/RefinedEDFeature.tsx"),
  "./components/mockups/homepage-sections/RefinedPartners.tsx": () => import("../components/mockups/homepage-sections/RefinedPartners.tsx"),
  "./components/mockups/homepage-sections/RefinedPillars.tsx": () => import("../components/mockups/homepage-sections/RefinedPillars.tsx"),
  "./components/mockups/report-banner/Current.tsx": () => import("../components/mockups/report-banner/Current.tsx"),
  "./components/mockups/report-banner/Mobile.tsx": () => import("../components/mockups/report-banner/Mobile.tsx"),
  "./components/mockups/ten-year-report/BlueReport.tsx": () => import("../components/mockups/ten-year-report/BlueReport.tsx"),
  "./components/mockups/ten-year-report/Current.tsx": () => import("../components/mockups/ten-year-report/Current.tsx")
};
